### ISSUE TITLE
A question about the calculation of the classification loss (I(Y|Z)) in VIB

### ISSUE THREAD

**Issue by xuewanqi** [udeepam/vib#1]
Thank you for this good tutorial about VIB!

I have a question about the classification loss (I(Y|Z)). It should be a expetation over z~p(z|x), then why don't sample many z from  p(z|x), and calculate E[-log(y|z)]? 
In my understand, the code just sample one z for each data to estimate the value ( in DeepVIB.reparameterise() function).

I wonder if these two implementation will cause any diffence in performance. I infer sample many z can better estimate the expectation value.

Thanks again!

**Comment by udeepam** [comment]
Hi xuewanqi. Sorry for the late reply!

You are correct that the code just samples one z for each estimate. This is mainly a design choice (stemming from the original VAE paper) and the [original authors ](https://arxiv.org/pdf/1612.00410.pdf) actually sample 12 times for the estimate.
